name: Build FarmHelper

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "FarmHelper ${{ github.ref_name }}"
          body: |
            ## 🌾 FarmHelper ${{ github.ref_name }}
            
            ### 📦 Installation
            1. Télécharge le `.jar` ci-dessous
          files: build/libs/*.jar
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
